---

- name: Install Java + Tomcat
  apt:
    state: present
    pkg:
      - tomcat8
      - openjdk-8-jdk-headless
      - libmysql-java # contains /usr/share/java/mysql.jar


- name: Add /etc/default/tomcat8 config file 
  copy: 
    src: tomcat8
    dest: /etc/default/tomcat8
  notify: restart tomcat


- name: create symlink for mysql dependency
  file:
    state: link
    src: /usr/share/java/mysql.jar
    dest: /var/lib/tomcat8/lib/mysql-connector-java.jar
    

- name: Copy servlet library
  copy:
    src: lib/servlet-api.jar
    dest: /var/lib/tomcat8/lib


- name: Copy json library
  copy:
    src: lib/json-simple.jar
    dest: /var/lib/tomcat8/lib


- name: Copy src files
  copy:
    src: src/
    dest: /opt/src
  tags: deploy-app


- name: Build class file for HelloWorld.java
  shell:
    cmd: javac -cp .:/var/lib/tomcat8/lib/servlet-api.jar HelloWorld.java
    chdir: /opt/src
  tags: deploy-app


- name: Build class file for GetAllEmployees.java
  shell:
    cmd: javac -cp .:/var/lib/tomcat8/lib/servlet-api.jar:/var/lib/tomcat8/lib/json-simple.jar GetAllEmployees.java
    chdir: /opt/src
  tags: deploy-app


- name: Build class file for Status.jar
  shell:
    cmd: javac -cp .:/var/lib/tomcat8/lib/servlet-api.jar:/var/lib/tomcat8/lib/json-simple.jar Status.java
    chdir: /opt/src
  tags: deploy-app


- name: Create webapp directory
  file:
    state: directory
    dest: /var/lib/tomcat8/webapps/api/WEB-INF/classes/
  tags: deploy-app

    
- name: Copy web.xml
  copy:
    src: web.xml
    dest: /var/lib/tomcat8/webapps/api/WEB-INF/web.xml
  tags: deploy-app


- name: Ansible sucks... let's do it this way
  find: 
    paths: /opt/src
    patterns: "*.class"
  register: all_class_files
  tags: deploy-app
  
  
- name: Copy class files
  copy:
    src: "{{ item.path }}"
    dest: /var/lib/tomcat8/webapps/api/WEB-INF/classes/
    remote_src: yes
  tags: deploy-app
  with_items: "{{ all_class_files.files }}"
  notify: restart tomcat
