---

- name: Install mariadb-server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python-pymysql


- name: clone test db from github
  git:
    repo: https://github.com/datacharmer/test_db
    dest: /opt/test_db

    
- name: enable BLACKHOLE module in mariadb
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mariadb
    option: plugin_load_add
    value: ha_blackhole
  notify: 
    - restart mariadb

    
- name: enable BLACKHOLE module in mariadb
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: bind-address
    value: 0.0.0.0
  notify: 
    - restart mariadb
    
    
- name: Fill database with dummy data
  shell: 
    cmd: mysql < employees.sql
    chdir: /opt/test_db
    creates: /var/lib/mysql/employees

- name: create db user for application
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: app
    password: secret-db-password
    host: '%'
    priv: "employees.*:ALL"
    state: present
